services:
  - type: web
    name: prontivus-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements-deploy.txt
    startCommand: python deploy_main.py
    envVars:
      - key: DATABASE_URL
        value: postgresql://prontibus_user:j1TNfXAeaD1fyNY5RPV68psq0JmwodLV@dpg-d38mtsogjchc73d6ovdg-a.oregon-postgres.render.com/prontibus
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: USE_SQLITE
        value: false
      - key: USE_DATABASE
        value: true
      - key: ALLOWED_ORIGINS
        value: https://healthcare-frontend-3.vercel.app,https://healthcare-frontend-3.vercel.app/,http://localhost:3000,http://localhost:8080
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0

# Database already exists on Render.com
# Database Name: postgres
# Username: prontivus_db_user
# Database: prontivus_db
# Connection: dpg-d38kvh15pdvs738m7np0-a.oregon-postgres.render.com:5432
