services:
  - type: web
    name: prontivus-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements-deploy.txt
    startCommand: python deploy_main.py
    envVars:
      - key: DATABASE_URL
        value: postgresql://prontivus_db_user:5lI6ouhUVLAuzL3ovjH8Hc929O60IuPU@dpg-d38kvh15pdvs738m7np0-a.oregon-postgres.render.com/prontivus_db
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: USE_SQLITE
        value: false
      - key: USE_DATABASE
        value: true
      - key: ALLOWED_ORIGINS
        value: https://prontivus-frontend.onrender.com,http://localhost:8080
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0

# Database already exists on Render.com
# Database Name: postgres
# Username: prontivus_db_user
# Database: prontivus_db
# Connection: dpg-d38kvh15pdvs738m7np0-a.oregon-postgres.render.com:5432
