services:
  - type: web
    name: prontivus-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements-deploy.txt
    startCommand: python deploy_main.py
    envVars:
      - key: DATABASE_URL
        sync: false  # Set this manually in Render dashboard
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: USE_SQLITE
        value: false
      - key: USE_DATABASE
        value: true
      - key: ALLOWED_ORIGINS
        value: https://prontivus-frontend.onrender.com,http://localhost:8080
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0

databases:
  - name: prontivus-db
    plan: free
    databaseName: prontivus_db
    user: prontivus_user
